package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Seeding must never overwrite. The bundled adapter is written out precisely
// so it can be EDITED; an upgrade that replaced an edited file would destroy
// the work and do it quietly -- the adapter would keep running, just not the
// way its author left it.
func TestSeedNeverOverwritesAnEditedAdapter(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir, err := ChatAdaptersDir()
	if err != nil {
		t.Fatal(err)
	}

	bundled := map[string][]byte{
		"telegram.js": []byte("// bundled v2\n"),
		"template.js": []byte("// template\n"),
	}

	// First run writes both.
	res, err := SeedChatAdapters(bundled)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Wrote) != 2 || len(res.Kept) != 0 {
		t.Fatalf("first seed wrote %d kept %d, want 2 and 0", len(res.Wrote), len(res.Kept))
	}

	// Somebody edits one of them.
	edited := filepath.Join(dir, "telegram.js")
	if err := os.WriteFile(edited, []byte("// MY EDIT\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	// Second run must keep it, byte for byte.
	res, err = SeedChatAdapters(bundled)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Wrote) != 0 || len(res.Kept) != 2 {
		t.Fatalf("second seed wrote %d kept %d, want 0 and 2", len(res.Wrote), len(res.Kept))
	}
	got, err := os.ReadFile(edited)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "// MY EDIT\n" {
		t.Fatalf("the edited adapter was overwritten: %q", got)
	}
}

// A bare name resolves inside the chat adapters dir; a path wins outright, so
// a local copy shadows a bundled adapter rather than fighting it.
func TestResolveChatScript(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	chatDir, err := ChatAdaptersDir()
	if err != nil {
		t.Fatal(err)
	}

	for _, tc := range []struct {
		name, in, want string
	}{
		{"bare name gets .js and the chat dir", "telegram", filepath.Join(chatDir, "telegram.js")},
		{"bare filename keeps its extension", "telegram.js", filepath.Join(chatDir, "telegram.js")},
		{"a relative path wins", "./mine/discord.js", "./mine/discord.js"},
		{"an absolute path wins", "/opt/a/discord.js", "/opt/a/discord.js"},
		{"a tilde is expanded, because people write them", "~/mine/discord.js", filepath.Join(home, "mine/discord.js")},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := ResolveChatScript(tc.in)
			if err != nil {
				t.Fatal(err)
			}
			if got != tc.want {
				t.Fatalf("ResolveChatScript(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}

	if _, err := ResolveChatScript(""); err == nil {
		t.Error("an empty script resolved; it must be an error")
	}
}

// The adapters directory sits beside config.toml, not in the state dir: an
// adapter is written by a person, like the config file, not generated by us.
func TestAdaptersDirIsBesideTheConfigFile(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	cfgPath, err := DefaultPath()
	if err != nil {
		t.Fatal(err)
	}
	adapters, err := AdaptersDir()
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Dir(cfgPath) != filepath.Dir(adapters) {
		t.Errorf("config.toml is in %s but adapters is in %s", filepath.Dir(cfgPath), filepath.Dir(adapters))
	}
	if !strings.HasSuffix(adapters, filepath.Join(".config", "herdr-expose", "adapters")) {
		t.Errorf("adapters dir = %s", adapters)
	}
}
